server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Pujakriti
    username: root
    password: password
  application:
    name: Pujakriti
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  config:
    import: optional:classpath:application.yaml
  mail:
    host: smtp.gmail.com
    port: 587
    username: pujakritishop@gmail.com
    password: zmlf tbpx tpul epqj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springdoc: DEBUG
    org.springframework.core.env: DEBUG